driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04
    driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    run_list:
      - recipe[apt]
  - name: centos-6.4
    driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
  - name: debian-7.2.0
    driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
  - name: source
    run_list:
      - recipe[nginx::default]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
      - recipe[nginx::repo]
      - recipe[nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: modules
    run_list:
      - recipe[nginx::source]
    attributes:
      nginx:
        modules:
          - nginx::headers_more_module
          - nginx::http_auth_request_module
          - nginx::http_echo_module
          - nginx::http_geoip_module
          - nginx::http_gzip_static_module
          - nginx::http_realip_module
          - nginx::http_spdy_module
          - nginx::http_ssl_module
          - nginx::http_stub_status_module
          - nginx::naxsi_module
          - nginx::ngx_devel_module
          - nginx::ngx_lua_module
          - nginx::openssl_source
          - nginx::upload_progress_module
